### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by RMatos2442** [jas-chen/atom-live-server#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package, v1.2.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, write

```
At fs.js:663

Error: EPERM: operation not permitted, write
  at Error (native)
  at Object.fs.writeSync (fs.js:663:20)
  at SyncWriteStream.write (fs.js:1932:6)
  at Array.logRequest (C:\Users\RMatos\.atom\packages\atom-live-server\live-server\node_modules\connect\node_modules\morgan\index.js:132:14)
  at listener (C:\Users\RMatos\.atom\packages\atom-live-server\live-server\node_modules\connect\node_modules\morgan\node_modules\on-finished\index.js:169:15)
  at onFinish (C:\Users\RMatos\.atom\packages\atom-live-server\live-server\node_modules\connect\node_modules\morgan\node_modules\on-finished\index.js:100:5)
  at callback (C:\Users\RMatos\.atom\packages\atom-live-server\live-server\node_modules\connect\node_modules\morgan\node_modules\on-finished\node_modules\ee-first\index.js:55:10)
  at ServerResponse.onevent (C:\Users\RMatos\.atom\packages\atom-live-server\live-server\node_modules\connect\node_modules\morgan\node_modules\on-finished\node_modules\ee-first\index.js:93:5)
  at emitNone (events.js:67:13)
  at ServerResponse.emit (events.js:166:7)
  at finish (_http_outgoing.js:525:10)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
     -7:06.8.0 welcome:show (atom-text-editor.editor.is-focused)
     -5:35.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -5:32.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:30.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:53 core:backspace (atom-text-editor.editor.is-focused)
     -2:52.1.0 editor:auto-indent (atom-text-editor.editor.is-focused)
  5x -2:46.5.0 pane:show-next-item (atom-text-editor.editor.is-focused)
  2x -2:27.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:25.1.0 core:save (atom-text-editor.editor.is-focused)
     -2:22.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:21.8.0 editor:auto-indent (atom-text-editor.editor.is-focused)
     -2:04.1.0 atom-live-server:start-3000 (ul.list-inline.tab-bar.inset-panel)
  2x -1:03.6.0 core:undo (atom-text-editor.editor.is-focused)
     -0:56.8.0 atom-live-server:start-3000 (atom-text-editor.editor.is-focused)
     -0:17.2.0 atom-live-server:start-9000 (atom-text-editor.editor.is-focused)
     -0:05.9.0 atom-live-server:start-3000 (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-live-server, v1.2.0

# Dev
No dev packages
```

**Comment by jas-chen** [comment]
@RMatos2442 please try v1.2.1, it should be solved.

**Comment by DanMcgraw** [comment]
Can you not gitignore, this needs to be modified:
atom-live-server\node_modules\live-server\index.js:45 replace \</body\> with \</head\>
