### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by IAMBESTMAN** [jas-chen/atom-live-server#105]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package 2.1.2

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At /usr/share/atom-beta/resources/app/src/buffered-process.js:392

Error: spawn ENOTDIR
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at BufferedProcess.spawn (/usr/share/atom-beta/resources/app/src/buffered-process.js:321:63)
    at BufferedProcess.start (/usr/share/atom-beta/resources/app/src/buffered-process.js:127:20)
    at new BufferedProcess (/usr/share/atom-beta/resources/app/src/buffered-process.js:112:18)
    at /packages/atom-live-server/lib/atom-live-server.js:130:23
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -2:08.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  2x -0:27.8.0 atom-live-server:startServer (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.5.0 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-ide-ui 0.3.3 
atom-live-server 2.1.2 
atom-material-ui 2.0.4 
atom-nodejs-snippets 2.0.0 
atom-react-autocomplete 0.1.10 
atom-terminal 0.8.0 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.7.0 
autoprefixer 3.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
custom-title 1.0.1 
docblockr 0.11.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
file-icons 2.1.11 
file-types 0.5.5 
git-plus 7.9.3 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-python 0.1.1 
ide-typescript 0.1.6 
intentions 1.1.5 
js-func-viewer 1.1.4 
js-hyperclick 1.11.0 
language-babel 2.74.2 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-ui-default 1.6.9 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
monokai 0.24.0 
my-package 0.0.0 
pigments 0.40.2 
react-es6-snippets 0.3.0 
react-redux-snippets 0.1.6 
react-snippets 0.9.0 
seti-ui 1.9.0 
simplified-chinese-menu 5.3.4 
```

**Comment by aditiapratama** [comment]
using atom beta 1.22 and this error showed up whenever I try to deploy live server

**Comment by ryanwarsaw** [comment]
I'm getting the same thing on Beta 1.22 on MacOS High Sierra.

**Comment by jas-chen** [comment]
plz upgrade to v2.2.0.
