### ISSUE TITLE
Uncaught TypeError: this.emit is not a function

### ISSUE THREAD

**Issue by Mtechnik** [jas-chen/atom-live-server#15]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.0-beta4
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package, v1.2.5
### Stack Trace

Uncaught TypeError: this.emit is not a function

```
At C:\Users\cross\.atom\packages\atom-live-server\live-server\node_modules\watchr\out\lib\watchr.js:355

TypeError: this.emit is not a function
    at C:\Users\cross\.atom\packages\atom-live-server\live-server\node_modules\watchr\out\lib\watchr.js:355:27
    at C:\Users\cross\.atom\packages\atom-live-server\live-server\node_modules\watchr\node_modules\bal-util\node_modules\safefs\out\lib\safefs.js:154:16
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -9:27.7.0 remote-ftp:create-ftp-config (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-atom-dark-syntax.theme-atom-dark-ui)
     -9:20.1.0 core:save (atom-text-editor.editor.is-focused)
     -9:10.6.0 atom-live-server:start-3000 (atom-text-editor.editor.is-focused)
     -8:35 core:save (atom-text-editor.editor.is-focused)
     -8:30.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -8:12.5.0 core:save (atom-text-editor.editor.is-focused)
     -8:11 core:undo (atom-text-editor.editor.is-focused)
     -8:10.7.0 core:save (atom-text-editor.editor.is-focused)
     -8:01.3.0 tree-view:remove (span.name.icon.icon-file-directory)
     -2:31.6.0 atom-terminal-panel:open-config (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-atom-dark-syntax.theme-atom-dark-ui)
     -2:10.8.0 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "command-palette",
      "preview-plus",
      "Remote-FTP"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-terminal-panel"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.19
atom-live-server, v1.2.5
atom-terminal-panel, v4.4.4
browser-refresh, v0.9.0
file-icons, v1.6.20

# Dev
No dev packages
```

**Comment by jas-chen** [comment]
I'm going to close this v1.x issue. Please upgrade to v2.0.0.
