### ISSUE TITLE
Failed to load the atom-live-server package

### ISSUE THREAD

**Issue by ReverendZen** [jas-chen/atom-live-server#169]
Cannot find module 'json5'
**Stack Trace**
Error: Cannot find module 'json5'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///C:/Users/rtrull/AppData/Local/atom/app-1.26.1/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (file:///C:/Users/rtrull/.atom/packages/atom-live-server-master/lib/atom-live-server.js:7:34)
    at Object.<anonymous> (file:///C:/Users/rtrull/.atom/packages/atom-live-server-master/lib/atom-live-server.js:154:2)
    at Module.get_Module._compile (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/rtrull/AppData/Local/atom/app-1.26.1/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\static\<embedded>:96:26)
    at Package.requireMainModule (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\package.js:782:33)
    at measure (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\package.js:143:22)
    at Package.measure (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\package.js:88:25)
    at Package.load (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\package.js:129:16)
    at PackageManager.loadAvailablePackage (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\package-manager.js:618:16)
    at PackageManager.loadPackage (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\package-manager.js:551:25)
    at PackageManager.disablePackage (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\src\package-manager.js:257:29)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\rtrull\AppData\Local\atom\app-1.26.1\resources\app\node_modules\settings-view\lib\package-card.js:364:31)

**Comment by samaresh007** [comment]
what is the solution

**Comment by swapnilgdata** [comment]
what is solution,
please update.

**Comment by dlwilson88** [comment]
Not sure if this is the fix but it worked for me. <br>
After receiving the same error message # as @ReverendZen <br>
I added _json5_ to my **atom-live-server** package.<br>
`npm install json5`<br>
Closed out and re-started Atom<br>
 I got another **error: cannot find strip-ansi**<br>
 So I added strip-ansi globally.<br>
<code>npm install -g strip-ansi</code><br>
And that fixed the problem for me. :satisfied:
