### ISSUE TITLE
Failed to load the atom-live-server package | Path must be a string. Received null

### ISSUE THREAD

**Issue by sjlee-jlp** [jas-chen/atom-live-server#199]
[Enter steps to reproduce:]

1. Download zip and unpack to: `C:\Users\userId\.atom\packages`
2. Load Atom.
3. Received error message about json5 not being installed.
4. Installed json5 using npm to: `C:\Users\userId\node_modules\json5`
5. Load Atom
6. Received error message about strip-ansi
7. Installed strip-ansi using npm to: `C:\Users\userId\node_modules\strip-ansi`

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package 2.3.0

### Stack Trace

Failed to load the atom-live-server package

```
At Path must be a string. Received null

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:501:7)
    at /packages/atom-live-server-master/lib/atom-live-server.js:12:25)
    at /packages/atom-live-server-master/lib/atom-live-server.js:192:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.30.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:782:33)
    at measure (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:143:22)
    at Package.measure (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:88:25)
    at Package.load (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:618:16)
    at config.transact (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:531:20)
    at Config.transact (~/AppData/Local/atom/app-1.30.0/resources/app/src/config.js:819:20)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.30.0/resources/app/src/atom-environment.js:837:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-easy-jsdoc 4.12.5 
cdn-libs 0.1.3 
html-to-css 0.2.2 
atom-live-server 2.3.0 
file-icons 2.1.24 
project-viewer 1.3.1 
autoclose-html 0.24.0 
autocomplete-gas 0.11.1 
atom-css-comb 3.3.1 
git-plus 8.1.0 
git-plus-toolbar 1.0.1 
highlight-selected 0.14.0 
ide-html 0.4.2 
ide-typescript 0.7.6 
linter-jshint 3.1.8 
linter 2.2.0 
minimap 4.29.8 
teletype 0.13.3 
```

**Comment by jcratwat** [comment]
I removed the folders and installed the package from within Atom instead (used the link on the Welcome tab) and it doesn't give me the error after relaunching.

**Comment by Shubhang-sharma** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: 'atom-live-server' package vundefined


### Stack Trace

Failed to load the atom-live-server package

```
At Invalid or unexpected token

C:\Users\Shubhang Sharma\.atom\packages\atom-live-server\lib\atom-live-server.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { 
                                                                                                                                                           

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:84:7)
    at NativeCompileCache.runInThisContext (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:148760)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149614)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3520819)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3507359
    at Package.measure (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3506159)
    at Package.load (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3506932)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:384071)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:382494
    at Config.transact (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:334439)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:382432)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:823411
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:825450)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by HansanaDasanayaka** [comment]
It Say's " Cannot find module 'json5'
Require stack:
- C:\Users\Hansana\.atom\packages\atom-live-server-master\lib\atom-live-server.js
- C:\Users\Hansana\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html "
