### ISSUE TITLE
Does not start in Atom 1.9.9

### ISSUE THREAD

**Issue by hutch120** [jas-chen/atom-live-server#24]
Hi, I've been using this awesome addon but I just upgraded to Atom 1.9.9 and I'm getting the error below when I try to start the webserver. Any ideas why? I tried reinstalling, but no effect.

```
Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2064:6)
    at Function.log (C:\Users\Admin\.atom\packages\atom-live-server\live-server\node_modules\connect\node_modules\debug\node.js:106:17)
    at enabled (C:\Users\Admin\.atom\packages\atom-live-server\live-server\node_modules\connect\node_modules\debug\debug.js:117:11)
    at Function.app.use (C:\Users\Admin\.atom\packages\atom-live-server\live-server\node_modules\connect\lib\proto.js:94:3)
    at Object.LiveServer.start (C:\Users\Admin\.atom\packages\atom-live-server\live-server\index.js:115:4)
    at file:///C:/Users/Admin/.atom/packages/atom-live-server/lib/atom-live-server.coffee:62:35
    at exports.allowUnsafeEval (C:\Users\Admin\.atom\packages\atom-live-server\node_modules\loophole\lib\loophole.js:14:14)
    at Object.module.exports.AtomLiveServer.startServer (file:///C:/Users/Admin/.atom/packages/atom-live-server/lib/atom-live-server.coffee:62:5)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-live-server:start-3000 (file:///C:/Users/Admin/.atom/packages/atom-live-server/lib/atom-live-server.coffee:18:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Admin\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Admin\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Admin\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Admin\AppData\Local\atom\app-1.9.9\resources\app.asar\src\atom-environment.js:1104:28)
    at EventEmitter.outerCallback (C:\Users\Admin\AppData\Local\atom\app-1.9.9\resources\app.asar\src\application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

**Comment by hutch120** [comment]
Fixed! I had set a windows environment system variable debug=* for other nodejs projects. This was causing one of the dependent modules to try and write a debug message which was failing.
