### ISSUE TITLE
atom-live-server is not installing

### ISSUE THREAD

**Issue by ArupDuttaBappy** [jas-chen/atom-live-server#265]
Installing “atom-live-server@2.3.0” failed.[Hide output…]

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\.atom\.apm\_logs\2020-10-22T14_43_54_412Z-debug.log

Opening "C:\Users\User\.atom\.apm\_logs\2020-10-22T14_43_54_412Z-debug.log"
.............
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\User\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\User\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\User\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\User\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/atom-live-server/versions/2.3.0/tarball',
1 verbose cli   '--target=6.1.12',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.4.0
4 verbose npm-session d366ac98a7380e8d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/jas-chen/atom-live-server/legacy.tar.gz/v2.3.0 4372ms (from cache)
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/atom-live-server/versions/2.3.0/tarball zlib: unexpected end of file
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 4470ms
11 verbose stack ZlibError: zlib: unexpected end of file
11 verbose stack     at Unzip.write (C:\Users\User\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:147:22)
11 verbose stack     at Unzip.flush (C:\Users\User\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:98:10)
11 verbose stack     at Unzip.end (C:\Users\User\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:104:10)
11 verbose stack     at Object.end (C:\Users\User\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\tar\lib\parse.js:421:21)
11 verbose stack     at PassThrough.onend (_stream_readable.js:675:10)
11 verbose stack     at Object.onceWrapper (events.js:288:20)
11 verbose stack     at PassThrough.emit (events.js:205:15)
11 verbose stack     at endReadableNT (_stream_readable.js:1154:12)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
12 verbose cwd C:\Users\User\AppData\Local\Temp\apm-install-dir-2020922-16016-164blat.0kuo
13 verbose Windows_NT 10.0.18362
14 verbose argv "C:\\Users\\User\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\User\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\User\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\User\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/atom-live-server/versions/2.3.0/tarball" "--target=6.1.12" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
15 verbose node v12.4.0
16 verbose npm  v6.14.8
17 error code Z_BUF_ERROR
18 error errno -5
19 error zlib: unexpected end of file
20 verbose exit [ -5, true ]

**Comment by ArupDuttaBappy** [comment]
[2020-10-16T18_21_35_864Z-debug.log](https://github.com/jas-chen/atom-live-server/files/5423581/2020-10-16T18_21_35_864Z-debug.log)
[2020-10-17T07_25_35_957Z-debug.log](https://github.com/jas-chen/atom-live-server/files/5423582/2020-10-17T07_25_35_957Z-debug.log)
[2020-10-17T07_26_09_429Z-debug.log](https://github.com/jas-chen/atom-live-server/files/5423583/2020-10-17T07_26_09_429Z-debug.log)
[2020-10-22T14_43_54_412Z-debug.log](https://github.com/jas-chen/atom-live-server/files/5423584/2020-10-22T14_43_54_412Z-debug.log)
[2020-10-22T14_44_11_618Z-debug.log](https://github.com/jas-chen/atom-live-server/files/5423585/2020-10-22T14_44_11_618Z-debug.log)
[2020-10-16T18_21_35_545Z-debug.log](https://github.com/jas-chen/atom-live-server/files/5423586/2020-10-16T18_21_35_545Z-debug.log)
[2020-10-16T18_21_35_549Z-debug.log](https://github.com/jas-chen/atom-live-server/files/5423587/2020-10-16T18_21_35_549Z-debug.log)
[2020-10-16T18_21_35_558Z-debug.log](https://github.com/jas-chen/atom-live-server/files/5423588/2020-10-16T18_21_35_558Z-debug.log)
[2020-10-16T18_21_35_573Z-debug.log](https://github.com/jas-chen/atom-live-server/files/5423589/2020-10-16T18_21_35_573Z-debug.log)

**Comment by ArupDuttaBappy** [comment]
I've tried too many times.

**Comment by god-like-010** [comment]
it just doesn't install, i tried like 20 times
