### ISSUE TITLE
Uncaught SyntaxError: Bad identifier as unquoted key at line 11 column 3 of the JSON5 data. Still...

### ISSUE THREAD

**Issue by Bdevn** [jas-chen/atom-live-server#267]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Debian GNU/Linux
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package 2.3.0

### Stack Trace

Uncaught SyntaxError: Bad identifier as unquoted key at line 11 column 3 of the JSON5 data. Still to read: "{\n     \"browser\" : \""

```
At /home/gg/.atom/packages/atom-live-server/node_modules/json5/lib/json5.js:64

SyntaxError: Bad identifier as unquoted key at line 11 column 3 of the JSON5 data. Still to read: "{\n     \"browser\" : \""
    at error (/packages/atom-live-server/node_modules/json5/lib/json5.js:56:25)
    at identifier (/packages/atom-live-server/node_modules/json5/lib/json5.js:112:17)
    at object (/packages/atom-live-server/node_modules/json5/lib/json5.js:454:31)
    at value (/packages/atom-live-server/node_modules/json5/lib/json5.js:482:20)
    at Object.parse (/packages/atom-live-server/node_modules/json5/lib/json5.js:508:18)
    at /packages/atom-live-server/lib/atom-live-server.js:137:34
    at /packages/atom-live-server/lib/atom-live-server.js:152:12
    at FSReqCallback.oncomplete (fs.js:153:23)
```

### Commands

```
  2x -4:17.7.0 editor:newline (input.hidden-input)
     -2:27.7.0 core:save-as (input.hidden-input)
     -1:52.9.0 tree-view:add-folder (span.name.icon.icon-repo)
     -1:43.8.0 core:confirm (input.hidden-input)
     -0:48.8.0 window:save-all (div.tool-panel.tree-view)
     -0:30.4.0 atom-live-server:startServer (input.hidden-input)
```

### Non-Core Packages

```
atom-file-icons 0.7.1 
atom-live-server 2.3.0 
busy-signal 2.0.1 
color-indent 1.1.0 
emmet 2.4.3 
highlight-selected 0.17.0 
intentions 1.1.5 
linter 3.1.1 
linter-ui-default 2.1.4 
minimap 4.29.9 
minimap-lens 0.8.1 
prettier-atom 0.60.1 
```

**Comment by Bdevn** [comment]
My apollogize, The issue was due to my creating a .json file to specify firefox developer edition as my default browser for Atom in my Debian 10 Buster system. I removed the file from my project and Live Server is working fine.
