### ISSUE TITLE
Failed to load the atom-live-server package

### ISSUE THREAD

**Issue by cliffordfajardo** [jas-chen/atom-live-server#43]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package 2.1.0

### Stack Trace

Failed to load the atom-live-server package

```
At Cannot find module 'json5'

Error: Cannot find module 'json5'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-live-server/lib/atom-live-server.js:7:34)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Commands

```
     -0:06.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-apex-snippets 0.3.3 
atom-beautify 0.29.17 
atom-bugs 0.24.0 
atom-clock 0.1.3 
atom-java-snippets 0.5.1 
atom-json-color 0.6.0 
atom-like-brackets-editor 1.1.4 
atom-live-server 2.1.0 
atom-mysql-snippets 0.3.1 
atom-python-snippets 0.0.0 
atom-trello 0.7.1 
atom-wrap-in-tag 0.6.0 
atomizr 0.23.0 
audio 1.5.7 
auto-id-class 0.2.6 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
autocomplete-html-entities 0.1.0 
autocomplete-json 5.2.0 
autocomplete-lodash 0.2.3 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.52 
autoupdate-packages 1.3.1 
battery-status 0.11.1 
browse 1.4.1 
browser-plus 0.0.87 
clipboard-autocomplete 0.4.0 
css-specificity 0.2.2 
dash 1.7.0 
docblockr 0.9.1 
double-tag 0.4.0 
edit-in-new-tab 0.9.0 
editorconfig 2.2.1 
emmet 2.4.3 
es6-javascript 1.0.0 
file-explorer 0.3.0 
file-icons 2.0.15 
file-watcher 1.0.2 
filesize 2.0.4 
gist 0.3.1 
git-clone 0.2.0 
git-log 0.4.1 
git-plus 7.2.2 
git-time-machine 1.5.6 
gitkraken 0.4.2 
highlight-column 0.5.2 
highlight-line 0.12.0 
highlight-selected 0.12.0 
Hydrogen 1.5.5 
jumpy 3.1.3 
kite 0.8.9 
language-babel 2.54.1 
language-gitignore 0.3.0 
linter 1.11.23 
linter-csslint 1.3.3 
linter-eslint 8.1.1 
linter-javac 1.9.4 
linter-jsonlint 1.3.0 
linter-pylama 0.8.13 
linter-sass-lint 1.7.4 
linter-shellcheck 1.4.3 
local-history 4.0.1 
mac-fix-path 0.0.0 
MavensMate-Atom 1.0.10 
maybs-quit 1.3.0 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.1 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-selection 4.4.0 
open-in-browser 0.4.7 
outline-selection 0.3.1 
package-manager-commands 2.0.3 
package-settings 1.1.0 
pane-layout-plus 0.7.3 
pane-move-plus 0.3.1 
pigments 0.39.0 
platformio-ide-terminal 2.2.3 
script 3.14.1 
set-syntax 0.3.2 
sort-lines 0.14.0 
split-diff 1.1.4 
Sublime-Style-Column-Selection 1.7.3 
svg-preview 0.11.0 
swackets 0.26.0 
symbol-gen 1.3.1 
sync-settings 0.8.1 
tag 0.4.0 
tree-view-autoresize 1.5.0 
tree-view-extended 1.0.0 
tree-view-git-status 1.3.0 
tree-view-search-bar 0.1.3 
web-accessibility-checker 0.1.4 
Zen 0.16.4 
```

**Comment by jas-chen** [comment]
Seems the install process is not complete. Uninstall the package and re-install it again.
