### ISSUE TITLE
Failed to load the atom-live-server package

### ISSUE THREAD

**Issue by papawolfe** [jas-chen/atom-live-server#44]
[Enter steps to reproduce below:]

1. Updating from v 1.5.0
2. Tried un-install/re-install but same error

**Atom Version**: 1.5.0
**System**: Mac OS X 10.12.3
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package, v2.1.1

### Stack Trace

Failed to load the atom-live-server package

```
At Cannot find module 'electron'

Error: Cannot find module 'electron'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Wolfe/.atom/packages/atom-live-server/lib/atom-live-server.js:6:60)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -4:28.8.0 core:close (atom-text-editor.editor.is-focused)
     -1:24.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-commander, v0.8.6
atom-live-server, v2.1.1
autoclose-html, v0.23.0
javascript-snippets, v1.2.1
open-in-browser, v0.4.7
pigments, v0.33.1

# Dev
No dev packages
```

**Comment by jas-chen** [comment]
Currently this package only support stable atom version. I'll keep eyes on the stable v1.5.0 release.

**Comment by jas-chen** [comment]
Okay, just tested atom-live-server v2.1.1 on atom v1.15.0-beta3 on macOS 10.12.3, everything works fine...

**Comment by papawolfe** [comment]
I didn't realize that Atom 1.5 wasn't a stable version. After deleting it and re-installing 1.14.3  everything works great. Thanks for making and maintaining this excellent package!
