### ISSUE TITLE
Failed to activate the atom-live-server package

### ISSUE THREAD

**Issue by ratik** [jas-chen/atom-live-server#5]
Hi,
I've installed the package and this error appeared when I tried to start the server.

**Atom Version**: 1.2.0
**System**: Windows 7
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package, v1.2.3

### Stack Trace

Failed to activate the atom-live-server package

```
At callSite.getFileName is not a function

TypeError: callSite.getFileName is not a function
    at callSiteLocation (C:\Users\Ratik\.atom\packages\atom-live-server\live-server\node_modules\connect\node_modules\depd\index.js:260:23)
    at depd (C:\Users\Ratik\.atom\packages\atom-live-server\live-server\node_modules\connect\node_modules\depd\index.js:120:14)
    at Object.<anonymous> (C:\Users\Ratik\.atom\packages\atom-live-server\live-server\node_modules\connect\lib\connect.js:12:32)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (C:\Users\Ratik\AppData\Local\atom\app-1.2.0\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Ratik\.atom\packages\atom-live-server\live-server\node_modules\connect\index.js:2:18)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (C:\Users\Ratik\AppData\Local\atom\app-1.2.0\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
     -0:08.5.0 atom-live-server:start-3000 (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-live-server, v1.2.3
node-debugger, v1.1.9

# Dev
No dev packages
```

**Comment by Nigh7Sh4de** [comment]
I too installed this yesterday and it was working fine for about 5-6 hours then started to fail in the same manner every time I tried to start the server.

**Comment by jas-chen** [comment]
@Nigh7Sh4de which OS do you use? Is Windows 7 too?

**Comment by jas-chen** [comment]
Please try v1.2.4, it should be fixed (at least on my machine).

**Comment by Nigh7Sh4de** [comment]
No I'm on Windows 10 but yeah the new update fixed it

**Comment by jas-chen** [comment]
Great!

**Comment by sagarssaurabh** [comment]
I m using mac and I have installed the package atom-live-server.
But I am unable to start lt, and although it appears to be installed in settings .
 it is not listed under the packages drop down. what should I do?
