### ISSUE TITLE
Uncaught SyntaxError: Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""

### ISSUE THREAD

**Issue by PaulDrozd** [jas-chen/atom-live-server#53]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package 2.1.2

### Stack Trace

Uncaught SyntaxError: Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""

```
At /Users/PaulDrozdFair/.atom/packages/atom-live-server/node_modules/json5/lib/json5.js:64

SyntaxError: Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""
    at error (/packages/atom-live-server/node_modules/json5/lib/json5.js:56:25)
    at word (/packages/atom-live-server/node_modules/json5/lib/json5.js:393:13)
    at value (/packages/atom-live-server/node_modules/json5/lib/json5.js:493:56)
    at Object.parse (/packages/atom-live-server/node_modules/json5/lib/json5.js:508:18)
    at /packages/atom-live-server/lib/atom-live-server.js:106:34
    at /packages/atom-live-server/lib/atom-live-server.js:121:12
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -2:21.6.0 dev-live-reload:reload-all (input.hidden-input)
  3x -1:53.2.0 atom-live-server:start-9000 (input.hidden-input)
     -1:30.2.0 atom-live-server:start-8000 (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:26.3.0 atom-live-server:start-4000 (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:23.3.0 atom-live-server:start-3000 (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:41.7.0 atom-live-server:stopServer (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:27.1.0 atom-live-server:startServer (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-bootstrap4 1.4.0 
atom-html-preview 0.1.22 
atom-live-server 2.1.2 
color-picker 2.2.5 
emmet 2.4.3 
git-plus 7.3.3 
gulp-control 0.5.0 
metro-ui 2.2.2 
minimap 4.27.0 
Remote-FTP 0.10.7 
sass-autocompile 0.13.3 
```

**Comment by Smaranika906** [comment]
when i run my html code it shows atom-live-server stopped what should i do ?

**Comment by tyt34** [comment]
I update **_json5_** through npm and remove empty file  **_.atom-live-server.json_** in project folder.
After, this erorr disappear.
