### ISSUE TITLE
Failed to load the atom-live-server package

### ISSUE THREAD

**Issue by byucoug2** [jas-chen/atom-live-server#60]
I see that this issue came up with a previous version of atom as listed on this page ( https://github.com/jas-chen/atom-live-server/issues/44 ). 

I'm seeing it in atom 1.17.2, which is what I get by default. Is this known to be broken there too? If so, will it be fixed? 

Error Message: 
Cannot find module 'json5'

Stack Trace: 
```
Error: Cannot find module 'json5'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\module-cache.js:354:1)
    at Module.require (file:///C:/Users/emstamps/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\native-compile-cache.js:66:1)
    at Object.<anonymous> (file:///C:/Users/emstamps/.atom/packages/atom-live-server-master/lib/atom-live-server.js:7:34)
    at Module.get_Module._compile (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\native-compile-cache.js:106:1)
    at Object.value [as .js] (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///C:/Users/emstamps/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\static\<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:887:1)
    at C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:158:1
    at Package.module.exports.Package.measure (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:99:1)
    at Package.module.exports.Package.load (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\package.js:144:1)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\package-manager.js:562:1)
    at C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\package-manager.js:476:1
    at Config.module.exports.Config.transact (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\config.js:321:1)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\package-manager.js:470:1)
    at C:\Users\emstamps\AppData\Local\atom\app-1.17.2\resources\app\src\atom-environment.js:798:1

```

**Comment by MYSTfan21** [comment]
Same message for me on a Windows 7 OS

**Comment by FrankenApps** [comment]
Same issue in Windows 7, but not in Windows 10
