### ISSUE TITLE
Failed to activate the atom-live-server package

### ISSUE THREAD

**Issue by lee978** [jas-chen/atom-live-server#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package, v1.2.5

### Stack Trace

Failed to activate the atom-live-server package

```
At Cannot find module 'loophole'

Error: Cannot find module 'loophole'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/User/.atom/packages/atom-live-server-master/lib/atom-live-server.coffee:2:21)
    at Object.<anonymous> (file:///C:/Users/User/.atom/packages/atom-live-server-master/lib/atom-live-server.coffee:1:1)
    at Module._compile (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:663:34)
    at Package.module.exports.Package.activateConfig (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:188:14)
    at Package.module.exports.Package.activateNow (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:166:14)
    at C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:740:25
    at Emitter.module.exports.Emitter.emit (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\User\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:1010:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:02.4.0 atom-live-server:start-8000 (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "browser-plus",
      "color-picker"
    ]
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.18.2

# Dev
No dev packages
```

**Comment by lee978** [comment]
I'm reinstall with command line and it works fine:
apm install atom-live-server
sorry, thanks.

**Comment by rgar22** [comment]
I'm still having the same problem, and I'm on Windows 7.

**Comment by forbible** [comment]
Cannot find module 'json5'
Hide Stack Trace
Error: Cannot find module 'json5'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/atom-live-server-master/lib/atom-live-server.js:7:34)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package.js:796:27)
    at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package.js:207:16)
    at C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package.js:96:15)
    at C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Administrator\AppData\Local\atom\app-1.15.0-beta2\resources\app.asar\src\package-manager.js:508:46)

**Comment by robsingh123** [comment]
-download stom-live-server from the website as zip
-unzip into.atom folder
-open cmd
-type apm install atom-live-serve and enter
-Restart Atom>settings>packages
-Find live server
-Click 'update'
-Restart Atom
