### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by shgysk8zer0** [jas-chen/atom-live-server#98]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: "Fedora release
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package 2.1.2

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At /usr/share/atom-beta/resources/app/src/buffered-process.js:392

Error: spawn ENOTDIR
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at BufferedProcess.spawn (/usr/share/atom-beta/resources/app/src/buffered-process.js:321:63)
    at BufferedProcess.start (/usr/share/atom-beta/resources/app/src/buffered-process.js:127:20)
    at new BufferedProcess (/usr/share/atom-beta/resources/app/src/buffered-process.js:112:18)
    at /packages/atom-live-server/lib/atom-live-server.js:130:23
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -6:38.3.0 intentions:highlight (input.hidden-input)
     -6:38.2.0 core:save (input.hidden-input)
  2x -5:56.1.0 datatip:toggle (input.hidden-input)
     -4:38.1.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
 12x -4:35.8.0 core:backspace (input.hidden-input)
     -4:23.3.0 editor:consolidate-selections (input.hidden-input)
     -4:23.3.0 core:cancel (input.hidden-input)
     -4:12.9.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -4:07.7.0 application:open-folder (atom-pane.pane)
     -3:39.2.0 grammar-selector:show (atom-text-editor.editor.enable-atom-ide-find-references.is-focused.has-selection)
  3x -2:29.2.0 symbols-view:go-to-declaration (span.syntax--meta.syntax--arguments.syntax--js)
  6x -1:18.1.0 datatip:toggle (input.hidden-input)
     -0:53.9.0 diagnostics:toggle-table (ul.list-inline.tab-bar.inset-panel)
     -0:37.6.0 github:toggle-git-tab (input.hidden-input)
     -0:35.3.0 github:toggle-github-tab (input.hidden-input)
     -0:09.8.0 atom-live-server:startServer (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-ide-ui 0.3.0 
atom-live-server 2.1.2 
atom-oss-license 1.1.1 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
file-icons 2.1.11 
gist-it 0.9.2 
gtk-dark-theme 0.1.4 
ide-php 0.6.1 
ide-typescript 0.6.1 
intentions 1.1.5 
language-apache 1.7.0 
language-ini 1.19.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-php 1.4.0 
linter-ui-default 1.6.8 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-autohide 0.10.1 
minimap-git-diff 4.3.1 
minimap-linter 2.0.2 
pandoc-convert 1.1.1 
```

**Comment by aditiapratama** [comment]
this issue affecting me as well
